spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
    username: postgres.tevkthgbqrysfjdxwkjq
    password: Araba123456!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
    cors:
      allowed-methods: true
      allowed-headers: true
      allowed-origins: true